-- DiscVault Next: canonical TMDB movie genre catalog + relational
-- movie_genres associations, replacing the legacy free-text
-- movies.metadata->>'genre' scalar (which stored comma-joined, possibly
-- combined and/or non-English labels).
--
-- TMDB genre ids are the source of truth: `genres.id` mirrors TMDB's
-- numeric movie genre id, `genres.key` is the stable ASCII key stored on
-- `movie_genres` and returned by the API. Locale labels are resolved only
-- at render time from the frontend i18n catalogs (`genre.<key>` keys) --
-- nothing here is locale-dependent.

CREATE TABLE IF NOT EXISTS genres (
    id         integer PRIMARY KEY,
    key        text UNIQUE NOT NULL,
    sort_order integer NOT NULL
);

INSERT INTO genres (id, key, sort_order) VALUES
    (28, 'action', 1),
    (12, 'adventure', 2),
    (16, 'animation', 3),
    (35, 'comedy', 4),
    (80, 'crime', 5),
    (99, 'documentary', 6),
    (18, 'drama', 7),
    (10751, 'family', 8),
    (14, 'fantasy', 9),
    (36, 'history', 10),
    (27, 'horror', 11),
    (10402, 'music', 12),
    (9648, 'mystery', 13),
    (10749, 'romance', 14),
    (878, 'science_fiction', 15),
    (10770, 'tv_movie', 16),
    (53, 'thriller', 17),
    (10752, 'war', 18),
    (37, 'western', 19)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS movie_genres (
    movie_id   uuid NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    genre_key  text NOT NULL REFERENCES genres(key) ON DELETE RESTRICT,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY (movie_id, genre_key)
);

CREATE INDEX IF NOT EXISTS idx_movie_genres_genre ON movie_genres(genre_key);

-- Audit trail for the one-time legacy `metadata->>'genre'` migration below.
-- Keeps the original raw text plus any tokens that couldn't be mapped to a
-- canonical genre, so unrecognized legacy data stays inspectable without
-- ever being surfaced as a genre.
CREATE TABLE IF NOT EXISTS movie_genre_migration_audit (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    movie_id        uuid NOT NULL REFERENCES movies(id) ON DELETE CASCADE,
    raw_value       text NOT NULL,
    matched_keys    jsonb NOT NULL DEFAULT '[]'::jsonb,
    unmatched_parts jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at      timestamptz NOT NULL DEFAULT now(),
    UNIQUE (movie_id)
);

-- Best-effort multilingual alias table used only by the one-time data
-- migration below, to map legacy free-text genre tokens (English, Dutch,
-- and every locale DiscVault ships translations for, plus a handful of
-- well-known abbreviations) onto the canonical genre keys above. Dropped
-- automatically when this migration's transaction commits.
CREATE TEMP TABLE _genre_alias_lookup (
    alias      text PRIMARY KEY,
    genre_key  text NOT NULL
) ON COMMIT DROP;

INSERT INTO _genre_alias_lookup (alias, genre_key) VALUES
        ('abenteuer', 'adventure'),
        ('acción', 'action'),
        ('actie', 'action'),
        ('actiefilm', 'action'),
        ('action', 'action'),
        ('acțiune', 'action'),
        ('adventure', 'adventure'),
        ('aile', 'family'),
        ('ajalooline', 'history'),
        ('akcija', 'action'),
        ('akcijas filma', 'action'),
        ('akció', 'action'),
        ('akcja', 'action'),
        ('aksiyon', 'action'),
        ('akční', 'action'),
        ('akčný', 'action'),
        ('animaatio', 'animation'),
        ('animacinis', 'animation'),
        ('animación', 'animation'),
        ('animacja', 'animation'),
        ('animasjon', 'animation'),
        ('animasyon', 'animation'),
        ('animatie', 'animation'),
        ('animation', 'animation'),
        ('animatsioon', 'animation'),
        ('animazione', 'animation'),
        ('animação', 'animation'),
        ('animație', 'animation'),
        ('animerat', 'animation'),
        ('animirani', 'animation'),
        ('animovaný', 'animation'),
        ('animációs', 'animation'),
        ('animācijas filma', 'animation'),
        ('aventura', 'adventure'),
        ('aventure', 'adventure'),
        ('aventură', 'adventure'),
        ('avonturenfilm', 'adventure'),
        ('avontuur', 'adventure'),
        ('avventura', 'adventure'),
        ('azione', 'action'),
        ('ação', 'action'),
        ('belgesel', 'documentary'),
        ('bilim kurgu', 'science_fiction'),
        ('bélica', 'war'),
        ('bűnügyi', 'crime'),
        ('ciencia ficción', 'science_fiction'),
        ('comedia', 'comedy'),
        ('comedie', 'comedy'),
        ('comedy', 'comedy'),
        ('commedia', 'comedy'),
        ('comédia', 'comedy'),
        ('comédie', 'comedy'),
        ('crime', 'crime'),
        ('crimen', 'crime'),
        ('crimă', 'crime'),
        ('családi', 'family'),
        ('detective', 'mystery'),
        ('detektyvas', 'mystery'),
        ('dobrodružný', 'adventure'),
        ('documentaire', 'documentary'),
        ('documentaire film', 'documentary'),
        ('documental', 'documentary'),
        ('documentar', 'documentary'),
        ('documentario', 'documentary'),
        ('documentary', 'documentary'),
        ('documentário', 'documentary'),
        ('dokumentaalfilm', 'documentary'),
        ('dokumentalny', 'documentary'),
        ('dokumentar', 'documentary'),
        ('dokumentarfilm', 'documentary'),
        ('dokumentarni', 'documentary'),
        ('dokumentinis', 'documentary'),
        ('dokumentti', 'documentary'),
        ('dokumentumfilm', 'documentary'),
        ('dokumentárny', 'documentary'),
        ('dokumentární', 'documentary'),
        ('dokumentär', 'documentary'),
        ('dokumentālā filma', 'documentary'),
        ('draama', 'drama'),
        ('drama', 'drama'),
        ('dramat', 'drama'),
        ('drame', 'drama'),
        ('drammatico', 'drama'),
        ('dramă', 'drama'),
        ('družinski', 'family'),
        ('dráma', 'drama'),
        ('drámai', 'drama'),
        ('drāma', 'drama'),
        ('eventyr', 'adventure'),
        ('famiglia', 'family'),
        ('familia', 'family'),
        ('familial', 'family'),
        ('familie', 'family'),
        ('familiefilm', 'family'),
        ('familijny', 'family'),
        ('familj', 'family'),
        ('family', 'family'),
        ('família', 'family'),
        ('fantaasia', 'fantasy'),
        ('fantascienza', 'science_fiction'),
        ('fantasia', 'fantasy'),
        ('fantasie', 'fantasy'),
        ('fantastik', 'fantasy'),
        ('fantastika', 'fantasy'),
        ('fantastinis', 'fantasy'),
        ('fantastique', 'fantasy'),
        ('fantastyka naukowa', 'science_fiction'),
        ('fantasy', 'fantasy'),
        ('fantasía', 'fantasy'),
        ('fantazija', 'fantasy'),
        ('fantezie', 'fantasy'),
        ('fantāzija', 'fantasy'),
        ('faroeste', 'western'),
        ('ficção científica', 'science_fiction'),
        ('film tv', 'tv_movie'),
        ('gerilim', 'thriller'),
        ('geschiedenis', 'history'),
        ('gizem', 'mystery'),
        ('glasba', 'music'),
        ('glazbeni', 'music'),
        ('griezelfilm', 'horror'),
        ('groază', 'horror'),
        ('grozljivka', 'horror'),
        ('guerra', 'war'),
        ('guerre', 'war'),
        ('gyser', 'horror'),
        ('histoire', 'history'),
        ('historia', 'history'),
        ('historický', 'history'),
        ('historie', 'history'),
        ('historisk', 'history'),
        ('history', 'history'),
        ('historyczny', 'history'),
        ('história', 'history'),
        ('horor', 'horror'),
        ('horreur', 'horror'),
        ('horror', 'horror'),
        ('hudební', 'music'),
        ('hudobný', 'music'),
        ('háborús', 'war'),
        ('istoric', 'history'),
        ('istorinis', 'history'),
        ('jännitys', 'thriller'),
        ('kaland', 'adventure'),
        ('kara filma', 'war'),
        ('karo', 'war'),
        ('kauhu', 'horror'),
        ('komedi', 'comedy'),
        ('komedia', 'comedy'),
        ('komedie', 'comedy'),
        ('komedie film', 'comedy'),
        ('komedija', 'comedy'),
        ('komédia', 'comedy'),
        ('komödie', 'comedy'),
        ('komöödia', 'comedy'),
        ('komēdija', 'comedy'),
        ('korku', 'horror'),
        ('kriegsfilm', 'war'),
        ('krig', 'war'),
        ('krim', 'crime'),
        ('krimi', 'crime'),
        ('kriminaal', 'crime'),
        ('kriminal', 'crime'),
        ('kriminalinis', 'crime'),
        ('kriminalistički', 'crime'),
        ('kriminalka', 'crime'),
        ('kryminał', 'crime'),
        ('liebesfilm', 'romance'),
        ('ljubavni', 'romance'),
        ('macera', 'adventure'),
        ('misdaad', 'crime'),
        ('misdaadfilm', 'crime'),
        ('mister', 'mystery'),
        ('misterija', 'mystery'),
        ('misterio', 'mystery'),
        ('mistero', 'mystery'),
        ('mistério', 'mystery'),
        ('mistērija', 'mystery'),
        ('mokslinė fantastika', 'science_fiction'),
        ('music', 'music'),
        ('musica', 'music'),
        ('musical', 'music'),
        ('musiikki', 'music'),
        ('musik', 'music'),
        ('musikk', 'music'),
        ('musique', 'music'),
        ('muusika', 'music'),
        ('muzical', 'music'),
        ('muziek', 'music'),
        ('muziekfilm', 'music'),
        ('muzikinis', 'music'),
        ('muzyczny', 'music'),
        ('mysteeri', 'mystery'),
        ('mysterie', 'mystery'),
        ('mysterium', 'mystery'),
        ('mysteriózny', 'mystery'),
        ('mysteriózní', 'mystery'),
        ('mystery', 'mystery'),
        ('mystère', 'mystery'),
        ('märulifilm', 'action'),
        ('mõistatus', 'mystery'),
        ('música', 'music'),
        ('müzik', 'music'),
        ('mūzikls', 'music'),
        ('noziegumu filma', 'crime'),
        ('nuotykių', 'adventure'),
        ('obiteljski', 'family'),
        ('oorlog', 'war'),
        ('oorlogsfilm', 'war'),
        ('película de televisión', 'tv_movie'),
        ('perefilm', 'family'),
        ('perhe', 'family'),
        ('piedzīvojumu filma', 'adventure'),
        ('povijesni', 'history'),
        ('przygodowy', 'adventure'),
        ('pustolovni', 'adventure'),
        ('pustolovščina', 'adventure'),
        ('ratni', 'war'),
        ('rejtély', 'mystery'),
        ('rikos', 'crime'),
        ('rodinný', 'family'),
        ('romance', 'romance'),
        ('romans', 'romance'),
        ('romantic', 'romance'),
        ('romantický', 'romance'),
        ('romantico', 'romance'),
        ('romantiek', 'romance'),
        ('romantiikka', 'romance'),
        ('romantik', 'romance'),
        ('romantika', 'romance'),
        ('romantikk', 'romance'),
        ('romantikus', 'romance'),
        ('romantinis', 'romance'),
        ('romantisk', 'romance'),
        ('război', 'war'),
        ('savaş', 'war'),
        ('sci fi', 'science_fiction'),
        ('sci-fi', 'science_fiction'),
        ('science fiction', 'science_fiction'),
        ('science-fiction', 'science_fiction'),
        ('sciencefiction', 'science_fiction'),
        ('scifi', 'science_fiction'),
        ('seikkailu', 'adventure'),
        ('seiklusfilm', 'adventure'),
        ('sf', 'science_fiction'),
        ('siaubo', 'horror'),
        ('skrekk', 'horror'),
        ('skrivnostni', 'mystery'),
        ('skräck', 'horror'),
        ('sota', 'war'),
        ('storia', 'history'),
        ('suspense', 'thriller'),
        ('suç', 'crime'),
        ('sõjafilm', 'war'),
        ('tajemnica', 'mystery'),
        ('tarih', 'history'),
        ('telefilme', 'tv_movie'),
        ('television film', 'tv_movie'),
        ('televizní film', 'tv_movie'),
        ('televízny film', 'tv_movie'),
        ('terror', 'horror'),
        ('thriller', 'thriller'),
        ('tieteiselokuva', 'science_fiction'),
        ('toiminta', 'action'),
        ('triler', 'thriller'),
        ('trileris', 'thriller'),
        ('triller', 'thriller'),
        ('tv film', 'tv_movie'),
        ('tv filma', 'tv_movie'),
        ('tv filmas', 'tv_movie'),
        ('tv filmi', 'tv_movie'),
        ('tv movie', 'tv_movie'),
        ('tv 영화', 'tv_movie'),
        ('tv-elokuva', 'tv_movie'),
        ('tv-film', 'tv_movie'),
        ('tvfilm', 'tv_movie'),
        ('tvムービー', 'tv_movie'),
        ('téléfilm', 'tv_movie'),
        ('tévéfilm', 'tv_movie'),
        ('történelmi', 'history'),
        ('ulme', 'science_fiction'),
        ('vahşi batı', 'western'),
        ('veiksmo', 'action'),
        ('vestern', 'western'),
        ('vesternas', 'western'),
        ('vesterns', 'western'),
        ('vojni', 'war'),
        ('vojnový', 'war'),
        ('válečný', 'war'),
        ('vígjáték', 'comedy'),
        ('vēsturiska filma', 'history'),
        ('war', 'war'),
        ('war film', 'war'),
        ('war movie', 'war'),
        ('western', 'western'),
        ('wojenny', 'war'),
        ('zgodovinski', 'history'),
        ('zinātniskā fantastika', 'science_fiction'),
        ('znanstvena fantastika', 'science_fiction'),
        ('äventyr', 'adventure'),
        ('õudusfilm', 'horror'),
        ('ģimenes filma', 'family'),
        ('šausmu filma', 'horror'),
        ('šeimos', 'family'),
        ('έγκλημα', 'crime'),
        ('γουέστερν', 'western'),
        ('δράμα', 'drama'),
        ('δράση', 'action'),
        ('επιστημονική φαντασία', 'science_fiction'),
        ('θρίλερ', 'thriller'),
        ('ιστορική', 'history'),
        ('κινούμενα σχέδια', 'animation'),
        ('κωμωδία', 'comedy'),
        ('μουσική', 'music'),
        ('μυστηρίου', 'mystery'),
        ('ντοκιμαντέρ', 'documentary'),
        ('οικογενειακή', 'family'),
        ('περιπέτεια', 'adventure'),
        ('πολεμική', 'war'),
        ('ρομαντική', 'romance'),
        ('τηλεοπτική ταινία', 'tv_movie'),
        ('τρόμου', 'horror'),
        ('φαντασία', 'fantasy'),
        ('анимация', 'animation'),
        ('анімація', 'animation'),
        ('бойовик', 'action'),
        ('вестерн', 'western'),
        ('военен', 'war'),
        ('військовий', 'war'),
        ('детектив', 'mystery'),
        ('документален', 'documentary'),
        ('документальний', 'documentary'),
        ('драма', 'drama'),
        ('екшън', 'action'),
        ('жахи', 'horror'),
        ('исторически', 'history'),
        ('комедия', 'comedy'),
        ('комедія', 'comedy'),
        ('криминален', 'crime'),
        ('кримінал', 'crime'),
        ('мистерия', 'mystery'),
        ('музика', 'music'),
        ('музикален', 'music'),
        ('наукова фантастика', 'science_fiction'),
        ('научна фантастика', 'science_fiction'),
        ('пригоди', 'adventure'),
        ('приключенски', 'adventure'),
        ('романтика', 'romance'),
        ('романтичен', 'romance'),
        ('семеен', 'family'),
        ('сімейний', 'family'),
        ('телевизионен филм', 'tv_movie'),
        ('телефільм', 'tv_movie'),
        ('трилер', 'thriller'),
        ('трилър', 'thriller'),
        ('уестърн', 'western'),
        ('фентезі', 'fantasy'),
        ('фентъзи', 'fantasy'),
        ('хорър', 'horror'),
        ('історичний', 'history'),
        ('アクション', 'action'),
        ('アドベンチャー', 'adventure'),
        ('アニメーション', 'animation'),
        ('コメディ', 'comedy'),
        ('スリラー', 'thriller'),
        ('ドキュメンタリー', 'documentary'),
        ('ドラマ', 'drama'),
        ('ファミリー', 'family'),
        ('ファンタジー', 'fantasy'),
        ('ホラー', 'horror'),
        ('ミステリー', 'mystery'),
        ('冒险', 'adventure'),
        ('冒險', 'adventure'),
        ('剧情', 'drama'),
        ('劇情', 'drama'),
        ('动作', 'action'),
        ('动画', 'animation'),
        ('動作', 'action'),
        ('動畫', 'animation'),
        ('历史', 'history'),
        ('喜剧', 'comedy'),
        ('喜劇', 'comedy'),
        ('奇幻', 'fantasy'),
        ('家庭', 'family'),
        ('恋愛', 'romance'),
        ('恐怖', 'horror'),
        ('悬疑', 'mystery'),
        ('惊悚', 'thriller'),
        ('愛情', 'romance'),
        ('懸疑', 'mystery'),
        ('战争', 'war'),
        ('戦争', 'war'),
        ('戰爭', 'war'),
        ('歴史', 'history'),
        ('歷史', 'history'),
        ('爱情', 'romance'),
        ('犯罪', 'crime'),
        ('电视电影', 'tv_movie'),
        ('科幻', 'science_fiction'),
        ('紀錄片', 'documentary'),
        ('纪录', 'documentary'),
        ('西部', 'western'),
        ('西部劇', 'western'),
        ('電視電影', 'tv_movie'),
        ('音乐', 'music'),
        ('音楽', 'music'),
        ('音樂', 'music'),
        ('驚悚', 'thriller'),
        ('가족', 'family'),
        ('공포', 'horror'),
        ('다큐멘터리', 'documentary'),
        ('드라마', 'drama'),
        ('로맨스', 'romance'),
        ('미스터리', 'mystery'),
        ('범죄', 'crime'),
        ('서부', 'western'),
        ('스릴러', 'thriller'),
        ('애니메이션', 'animation'),
        ('액션', 'action'),
        ('어드벤처', 'adventure'),
        ('역사', 'history'),
        ('음악', 'music'),
        ('전쟁', 'war'),
        ('코미디', 'comedy'),
        ('판타지', 'fantasy')
;

-- Tokenize every legacy combined genre string (split on comma/slash/pipe/
-- semicolon/ampersand and a handful of language-neutral conjunctions), then
-- alias-map each token. Kept in a temp table so the insert and the audit
-- trail below are computed from a single, consistent tokenization pass.
CREATE TEMP TABLE _genre_migration_tokens ON COMMIT DROP AS
SELECT
    m.id AS movie_id,
    trim(m.metadata->>'genre') AS raw_value,
    trim(token) AS token,
    lookup.genre_key AS genre_key
FROM movies m
CROSS JOIN LATERAL regexp_split_to_table(
    trim(m.metadata->>'genre'),
    '\s*(?:,|/|\||;|&|、|・)\s*|\s+(?:and|en|und|et)\s+',
    'i'
) AS token
LEFT JOIN _genre_alias_lookup lookup ON lower(trim(token)) = lookup.alias
WHERE m.metadata ? 'genre'
  AND trim(COALESCE(m.metadata->>'genre', '')) <> '';

DELETE FROM _genre_migration_tokens WHERE token = '';

INSERT INTO movie_genres (movie_id, genre_key)
SELECT DISTINCT movie_id, genre_key
FROM _genre_migration_tokens
WHERE genre_key IS NOT NULL
ON CONFLICT (movie_id, genre_key) DO NOTHING;

INSERT INTO movie_genre_migration_audit (movie_id, raw_value, matched_keys, unmatched_parts)
SELECT
    movie_id,
    max(raw_value),
    COALESCE(jsonb_agg(DISTINCT genre_key) FILTER (WHERE genre_key IS NOT NULL), '[]'::jsonb),
    COALESCE(jsonb_agg(DISTINCT token) FILTER (WHERE genre_key IS NULL), '[]'::jsonb)
FROM _genre_migration_tokens
GROUP BY movie_id
ON CONFLICT (movie_id) DO NOTHING;

-- The legacy scalar is fully superseded by movie_genres; drop it so no code
-- path can accidentally read a stale combined-string genre value again.
UPDATE movies SET metadata = metadata - 'genre' WHERE metadata ? 'genre';

-- Genre is no longer a lockable field (it is read-only and TMDB-owned), so
-- drop any stale "genre" entry left over in a movie's field lock list.
UPDATE movies
SET metadata = jsonb_set(
    metadata,
    '{field_locks}',
    COALESCE(
        (
            SELECT jsonb_agg(value)
            FROM jsonb_array_elements(metadata->'field_locks') AS value
            WHERE value <> '"genre"'::jsonb
        ),
        '[]'::jsonb
    )
)
WHERE metadata->'field_locks' @> '["genre"]'::jsonb;

UPDATE movies
SET metadata = jsonb_set(
    metadata,
    '{fieldLocks}',
    COALESCE(
        (
            SELECT jsonb_agg(value)
            FROM jsonb_array_elements(metadata->'fieldLocks') AS value
            WHERE value <> '"genre"'::jsonb
        ),
        '[]'::jsonb
    )
)
WHERE metadata->'fieldLocks' @> '["genre"]'::jsonb;
